### ISSUE TITLE
Problem moving from temp cert to permanent cert

### ISSUE THREAD

**Issue by ninagran** [IdentityServer/IdentityServer4#603]
On Windows 2012 R2 IIS8.5 - IdSrv4 with temp cert (SetTemporarySigningCredential) works fine with Cordova and browser clients. Trying to make it work with a self-signed cert (SetSigningCredential("CN=IDServ")). I see keys at jwks_uri. I open a client, enter credentials in the IdSrv login form, and then I get an error upon return. I tried from Cordova (popup) and browser (redirect) - neither works with the permanent cert but do work with the temp cert. The error is:

System.Security.Cryptography.CryptographicException: OpenCSP failed with error code 2148073494.
   at Internal.NativeCrypto.CapiHelper.CreateProvHandle(CspParameters parameters, Boolean randomKeyContainer)
   at System.Security.Cryptography.RSACryptoServiceProvider.get_SafeProvHandle()
   at System.Security.Cryptography.RSACryptoServiceProvider.get_SafeKeyHandle()
   at System.Security.Cryptography.RSACryptoServiceProvider..ctor(Int32 keySize, CspParameters parameters, Boolean useDefaultKeySize)
   at Internal.Cryptography.Pal.CertificatePal.<>c.<GetRSAPrivateKey>b__59_0(CspParameters csp)
   at Internal.Cryptography.Pal.CertificatePal.GetPrivateKey[T](Func`2 createCsp, Func`2 createCng)
   at Internal.Cryptography.Pal.CertificateExtensionsCommon.GetPrivateKey[T](X509Certificate2 certificate, Predicate`1 matchesConstraints)
   at Microsoft.IdentityModel.Tokens.X509SecurityKey.get_PrivateKey()
   at Microsoft.IdentityModel.Tokens.X509SecurityKey.get_HasPrivateKey()
   at Microsoft.IdentityModel.Tokens.AsymmetricSignatureProvider..ctor(SecurityKey key, String algorithm, Boolean willCreateSignatures)
   at Microsoft.IdentityModel.Tokens.CryptoProviderFactory.CreateProvider(SecurityKey key, String algorithm, Boolean willCreateSignatures)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.CreateEncodedSignature(String input, SigningCredentials signingCredentials)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.WriteToken(SecurityToken token)
   at IdentityServer4.Services.Default.DefaultTokenCreationService.CreateJwtAsync(JwtSecurityToken jwt)
   at IdentityServer4.Services.Default.DefaultTokenCreationService.<CreateTokenAsync>d__2.MoveNext()

**Comment by leastprivilege** [comment]
I have seen similar issues before - search the dotnet repos if this has been fixed or not.

**Comment by ninagran** [comment]
I found your reference to the issue in CoreFx but the issue there is from 1.5 years. Can you tell me if you have run IdSrv4 with .Net Core on a server with a permanent self-signed cert. If yes, what Windows and IIS? Thanks.

**Comment by leastprivilege** [comment]
Not sure what platform they are using on Azure Web Apps - but both temp credentials and X509 works fine there.

Closing for now - feel free to re-open when you have more info/questions

**Comment by dsund** [comment]
@ninagran Did you solve this issue? I'm experiencing the same thing.

**Comment by leastprivilege** [comment]
This particular issue with certs has been fixed in 1.1.1

**Comment by ninagran** [comment]
@dsund We have not solved that for the original IdSrv. I just started a new one with "IdentityServer4.AspNetIdentity": "1.0.0", hopefully that will work.
